In [43]:
import os
import numpy as np
import pandas as pd
import  matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split # for training and testing
from sklearn.linear_model import LogisticRegression  # binary classification problem ko solve krti h , activation function(nonlinear--> linear),

In [44]:
df = pd.read_csv(r'G:\project\loan_approval\data\loan_approval.csv')
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False


In [45]:
df.drop('city',axis =1, inplace=True)


In [46]:
#df.drop('points',axis =1, inplace=True)

In [47]:
df.drop('years_employed',axis =1, inplace=True)

In [48]:
df.drop('name',axis=1,inplace=True)

In [49]:
df

,income,credit_score,loan_amount,points,loan_approved
0,113810,389,39698,50.0,False
1,44592,729,15446,55.0,False
2,33278,584,11189,45.0,False
3,127196,344,48823,50.0,False
4,66048,496,47174,25.0,False
...,...,...,...,...,...
1995,92163,770,12251,85.0,True
1996,38799,635,48259,40.0,False
1997,41957,763,16752,60.0,True
1998,139022,360,24031,55.0,False


In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.isnull().sum()

income           0
credit_score     0
loan_amount      0
points           0
loan_approved    0
dtype: int64

In [52]:
# 'df' is your cleaned DataFrame
 # df.to_csv('cleaned_data.csv', index=False)

In [53]:
df = pd.read_csv('G:\project\loan_approval\data\cleaned_data.csv')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\hp\AppData\Local\Temp\ipykernel_19904\2259159946.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('G:\project\loan_approval\data\cleaned_data.csv')


In [54]:
x = df.drop('loan_approved',axis=1)
y = df[['loan_approved']]

In [55]:
x_train, x_test, y_train, y_test =train_test_split(x , y,test_size=0.2,random_state=42) # here test size is the data we want to test on and random state is the data we want t otrain max

In [56]:
x_train

,income,credit_score,loan_amount,points
968,49973,464,22397,25.0
240,70306,508,22644,35.0
819,88446,798,17896,85.0
692,70538,367,13343,45.0
420,96562,763,8472,85.0
...,...,...,...,...
1130,102140,495,48455,45.0
1294,107993,477,42635,35.0
860,83424,579,17117,50.0
1459,133247,392,13095,60.0


In [57]:
x_test

,income,credit_score,loan_amount,points
1860,130290,447,16496,55.0
353,54050,808,10217,85.0
1333,105529,698,32169,75.0
905,74057,648,6627,65.0
1289,39359,802,12388,70.0
...,...,...,...,...
965,139999,402,49121,50.0
1284,49528,584,47618,35.0
1739,124924,331,6481,60.0
261,64741,742,13172,80.0


In [58]:
y_train

,loan_approved
968,False
240,False
819,True
692,False
420,True
...,...
1130,False
1294,False
860,False
1459,True


In [59]:
y_test

,loan_approved
1860,False
353,True
1333,True
905,True
1289,True
...,...
965,False
1284,False
1739,True
261,True


In [60]:
print(df["loan_approved"].value_counts())


loan_approved
False    1121
True      879
Name: count, dtype: int64


In [61]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1600, 4), (400, 4), (1600, 1), (400, 1))

In [62]:
print(x.columns)

Index(['income', 'credit_score', 'loan_amount', 'points'], dtype='object')


In [63]:
from sklearn.model_selection import train_test_split # for training and testing
from sklearn.linear_model import LogisticRegression
log = LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train.values.ravel())

g:\project\loan_approval\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [64]:
from sklearn.svm import SVC
import joblib

In [65]:
sv = SVC()
sv.fit(x_train, y_train.values.ravel())
print("Test Score -->", sv.score(x_test, y_test.values.ravel()))       
print("Training score-->", sv.score(x_train, y_train.values.ravel()))


Test Score --> 0.5975
Training score--> 0.63


In [66]:
joblib.dump(sv,'sv_load.lb')

['sv_load.lb']

In [67]:
model = joblib.load('sv_load.lb')
model

,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [68]:
model.predict(x_test)

array([ True, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False,  True,

In [69]:
pred = log.predict(x_test)

In [70]:
pred

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
        True, False, False,  True, False,  True,  True, False, False,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True, False,

In [71]:
y_test

,loan_approved
1860,False
353,True
1333,True
905,True
1289,True
...,...
965,False
1284,False
1739,True
261,True


In [72]:
# Accuracy
print("Test Score -->",log.score(x_test,y_test))       
print("Training score-->",log.score(x_train,y_train))

Test Score --> 1.0
Training score--> 1.0


In [73]:
joblib.dump(log,'log_load.lb')

['log_load.lb']

In [74]:
model = joblib.load('log_load.lb')
model

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [75]:
model.predict(x_test)

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
        True, False, False,  True, False,  True,  True, False, False,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True, False,

In [76]:
pred = log.predict(x_test)

In [77]:
pred

array([False,  True,  True,  True,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False, False,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False, False, False,
        True, False, False,  True, False,  True,  True, False, False,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False,  True,  True, False, False,  True,  True,
        True, False,

In [78]:
# Accuracy
print("Test Score -->",log.score(x_test,y_test))       
print("Training score-->",log.score(x_train,y_train))

Test Score --> 1.0
Training score--> 1.0


In [79]:
sample = [[12000, 200, 1200000, 200]]

print("Logistic:", log.predict(sample))
print("SVM:", sv.predict(sample))

Logistic: [ True]
SVM: [ True]


g:\project\loan_approval\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
g:\project\loan_approval\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [80]:
print(df.describe())

              income  credit_score   loan_amount       points
count    2000.000000   2000.000000   2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000    56.680000
std     34487.874907    160.564945  14207.320147    18.638033
min     30053.000000    300.000000   1022.000000    10.000000
25%     61296.250000    433.000000  12748.750000    45.000000
50%     90387.500000    576.000000  25661.500000    55.000000
75%    120099.750000    715.000000  37380.500000    70.000000
max    149964.000000    850.000000  49999.000000   100.000000


In [81]:
coef = pd.DataFrame({
    "Feature": x.columns,
    "Coefficient": log.coef_[0]
})

print(coef.sort_values("Coefficient", ascending=False))

        Feature  Coefficient
3        points     2.299986
1  credit_score     0.004743
0        income     0.000006
2   loan_amount    -0.000019


In [82]:
from sklearn.metrics import accuracy_score

pred = log.predict(x_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 1.0


In [83]:
if points > 60:
    loan_approved = True

NameError: name 'points' is not defined

In [84]:
print(df.corr(numeric_only=True))

                 income  credit_score  loan_amount    points  loan_approved
income         1.000000     -0.027113     0.037612  0.451142       0.238066
credit_score  -0.027113      1.000000    -0.008076  0.740899       0.715788
loan_amount    0.037612     -0.008076     1.000000 -0.223039      -0.157859
points         0.451142      0.740899    -0.223039  1.000000       0.821415
loan_approved  0.238066      0.715788    -0.157859  0.821415       1.000000


In [85]:
if points > threshold:
    loan_approved = True
else:
    loan_approved = False

NameError: name 'points' is not defined